/** Plain-language, phone-first instructions for posting a listing on each marketplace.
 *  Written for someone who has never sold online. Apps move buttons around; steps stay close enough to follow. */
export interface HowTo { app: string; fees: string; bestFor: string; firstTime?: string[]; before: string[]; steps: string[]; tips: string[] }

export const HOWTO: Record<string, HowTo> = {
  facebook: {
    app: "Facebook Marketplace",
    fees: "Free for local pickup. If you ship through Facebook, they take 5% (min 40¢).",
    bestFor: "Anything local: furniture, tools, lamps, electronics, big items.",
    firstTime: [
      "You need a regular Facebook account; Marketplace is inside it. New accounts sometimes can't list for a few days; that's normal, just wait.",
      "Facebook may ask you to confirm your phone number the first time you sell.",
      "Buyers message you in Messenger. \"Is this still available?\" is an automatic button; answer \"Yes\" and ask when they can pick up.",
    ],
    before: ["Save the item's photos to your phone (press and hold a photo above → Save).", "Have the Facebook app installed and be signed in."],
    steps: [
      "Open Facebook. Tap the Marketplace icon (the little storefront at the bottom or in the ≡ menu).",
      "Tap \"Sell\" (or \"+ Create new listing\"), then \"Items\".",
      "Tap \"Add photos\" and pick the photos you saved. Choose up to 10. The first one is the cover.",
      "Title: paste the first line from the copy above (press and hold in the box → Paste).",
      "Price: type the price. Category: pick the closest one (Facebook suggests one; check it).",
      "Condition: pick the one that matches what's above.",
      "Description: paste the rest of the copy.",
      "Location: your town. Leave \"Hide from friends\" off unless you want that.",
      "Tap \"Next\". If it offers to post to groups too, tick your local buy/sell groups and this app's group.",
      "Tap \"Publish\". It's live. Messages come to Messenger.",
    ],
    tips: ["Keep it to real items with their real price (never $1 to get attention), and no web addresses or phone numbers in the listing; Facebook hides those.", "Answer \"Is this available?\" fast; Facebook ranks quick responders higher.", "Renew the listing every 7 days (Marketplace → Your listings → Renew) to stay near the top.", "Meet in a public place or at the warehouse; cash or Zelle in person only."],
  },
  offerup: {
    app: "OfferUp",
    fees: "Free for local. Shipping sales: 12.9% (min $1.99).",
    bestFor: "Local buyers, electronics, tools, furniture. Strong in cities.",
    firstTime: [
      "Sign up with your phone number; it texts you a code.",
      "It'll ask to use your location so buyers nearby can see your item. Say yes.",
      "\"TruYou\" is a one-time ID check (driver's license photo). Optional, but buyers trust it.",
    ],
    before: ["Save the photos to your phone.", "Install the OfferUp app and create an account (phone number verification)."],
    steps: [
      "Open OfferUp. Tap the big \"Post\" button at the bottom.",
      "Tap \"Take photo\" or the gallery icon and choose your saved photos (up to 12).",
      "Title: paste the title. Category: pick one. Condition: pick one.",
      "Description: paste the copy above.",
      "Price: type it. Turn \"Firm on price\" off; OfferUp buyers expect to haggle.",
      "Delivery: tick \"Local pickup\" and, if you'll ship, \"Shipping\" (OfferUp gives you a prepaid label; the buyer pays for it).",
      "Tap \"Post\". Done.",
    ],
    tips: ["One listing per item, your own photos (not stock pictures), and no phone numbers, emails, social handles or web addresses anywhere; OfferUp removes those.", "Add your ZIP so it shows in local search.", "Use \"Promote\" only for items over $100; it costs a few dollars.", "Verify your profile (TruYou) once; buyers trust it."],
  },
  ebay: {
    app: "eBay",
    fees: "About 13.6% of the total (item + shipping) plus 30¢ per order for most categories. Free to list (250 a month).",
    bestFor: "Anything shippable with brand names: audio, tools, parts, collectibles, vintage. Biggest audience.",
    firstTime: [
      "Signing up asks for your name, address, phone, and a bank account for payouts. It may ask for a photo of your ID; that's normal for everyone, it's the law for payment companies.",
      "\"Handling time\" = how many days you need to get it in the mail after they pay. Pick 1 or 2.",
      "\"Item specifics\" = brand, model, color, size boxes. Fill in what you know; skip the rest.",
      "Your first payouts can take a few extra days while eBay checks the account. After that it's 1-2 days.",
    ],
    before: ["Save the photos.", "Install the eBay app, create an account, add a payout bank account (Payments → Set up)."],
    steps: [
      "Open eBay. Tap \"Selling\" at the bottom, then \"List an item\".",
      "Type the brand and model in the search box. If eBay finds a matching product, tap it; it fills in specs for you. If not, tap \"Create a new listing\".",
      "Tap \"Add photos\" and choose up to 24. First photo = main photo; plain background helps.",
      "Title: paste the 80-character title from the copy. Every word counts for search; no \"L@@K\".",
      "Condition: choose it and add the condition notes.",
      "Item specifics: fill in brand, model, type, color. More = better search placement.",
      "Description: paste the description.",
      "Format: \"Buy It Now\" for most things. For rare items with no clear price, choose \"Auction\", 7 days, start at 99¢ only if you're sure it'll get bids.",
      "Price: eBay shows what similar items sold for; tap that to see. Turn on \"Allow offers\".",
      "Shipping: \"Calculated\" with the weight and box size, or \"Flat\" if you know the cost. Tick \"Local pickup\" too if you want.",
      "Returns: 30 days is the norm and gets a search boost; \"No returns\" is allowed.",
      "Tap \"List it\". Buyers pay through eBay; you ship within your handling time, and eBay pays your bank in 1–2 days.",
    ],
    tips: ["One listing per item: eBay doesn't allow two fixed-price listings of the same item at the same time. No links, web addresses, phone numbers or emails in the listing.", "Check \"Sold items\" (search → Filter → Sold) before pricing; that's the real market.", "Print eBay's shipping labels in the app; they're cheaper than the post office counter.", "Ship within a day and buyers rate you higher, which raises your listings."],
  },
  craigslist: {
    app: "Craigslist",
    fees: "Free for almost everything (cars and some services cost $5).",
    bestFor: "Local, cash, older buyers, contractors, big items, lots and pallets.",
    firstTime: [
      "No app needed; it's a website. Make an account with your email.",
      "Craigslist may charge $5 for some categories (cars, furniture in big cities). Most are free.",
      "Buyers email you through a hidden Craigslist address; your real email isn't shown.",
    ],
    before: ["Save the photos.", "Go to craigslist.org in your phone's browser and pick your city."],
    steps: [
      "Tap \"create a posting\" (top left).",
      "Choose \"for sale by owner\", then the category closest to your item.",
      "Posting title: paste the title. Price: type it. Postal code: yours.",
      "Description: paste the copy.",
      "Contact: choose \"CL mail relay\" so your email stays hidden. Add a phone only if you want texts.",
      "Tap \"continue\". Add a map location if you like (or just the town).",
      "Tap \"add images\" and upload your photos (up to 24).",
      "Tap \"done with images\", check the preview, tap \"publish\".",
      "Check your email and click the confirmation link. Without that click the ad never goes live.",
    ],
    tips: ["Post each item once, and repost no more than once every 48 hours. No keyword lists and no links to other selling sites; Craigslist flags those.", "Renew every 48 hours (the email link or your account page) to jump back to the top.", "Craigslist has scammers offering to pay by check or \"send a mover\". Cash in person only.", "One item per ad works better than a long list."],
  },
  mercari: {
    app: "Mercari",
    fees: "Currently no seller fee; the buyer pays a service fee at checkout. (Mercari has changed this before; check the app.)",
    bestFor: "Shippable items under $200: electronics, kitchen, toys, small collectibles.",
    firstTime: [
      "Sign up with email or phone. To get paid you add a bank account under Settings, then Payments.",
      "Mercari holds the money until the buyer says they got it (3 days after delivery at most). That's how it protects both sides.",
      "\"Smart pricing\" lowers your price automatically over time; turn it off if you want your number to stick.",
    ],
    before: ["Save the photos.", "Install Mercari and create an account; add your bank for payouts."],
    steps: [
      "Open Mercari. Tap \"Sell\" (the camera icon at the bottom).",
      "Add up to 12 photos.",
      "Title: paste the title. Description: paste the copy.",
      "Category, brand, condition: pick them.",
      "Shipping: choose \"Mercari prepaid label\" and enter the weight; pick who pays (buyer-paid shipping is normal).",
      "Price: type it. Turn on \"Smart Pricing\" only if you're happy with the floor price it asks for.",
      "Tap \"List\". When it sells, print the label from the app and ship within 3 days.",
    ],
    tips: ["One listing per item, and keep hashtags to 3 that describe the item. Never add other brand names or a long keyword list; Mercari removes those.", "Promote (drop the price 5%) once a week; Mercari notifies people who liked it.", "Package well; the buyer has 3 days to rate before you're paid."],
  },
  poshmark: {
    app: "Poshmark",
    fees: "20% on sales over $15; flat $2.95 under $15. Buyer pays shipping.",
    bestFor: "Clothing, shoes, handbags, home décor, and some electronics. Brand names sell.",
    firstTime: [
      "Made for clothes, shoes, and bags; other stuff is allowed under Home and Electronics.",
      "Sign up with email. Poshmark sends you a prepaid shipping label for every sale; you just tape it on.",
      "\"Offer to likers\" lets you send a discount to people who liked your item; it's the main way things sell there.",
    ],
    before: ["Save the photos; square photos look best.", "Install Poshmark and create an account."],
    steps: [
      "Open Poshmark. Tap \"Sell\" at the bottom.",
      "Add up to 16 photos. The first is the \"covershot\"; make it clean.",
      "Title: paste the title (80 characters max). Description: paste the copy.",
      "Category, size (if clothing), brand, color, condition: pick them.",
      "Original price and Listing price: fill both (Poshmark shows the markdown).",
      "Tap \"List this item\".",
      "Buyers pay Poshmark; you get a prepaid USPS label by email. Ship within 2 days.",
    ],
    tips: ["Only clothing, shoes, bags, home goods and electronics. Never put your phone number or email in a listing.", "Share your listing to your followers daily and join \"Posh Parties\"; that's how things get seen.", "Price 20–30% above your bottom line and accept reasonable offers.", "Add measurements for anything clothing or furniture."],
  },
  vinted: {
    app: "Vinted",
    fees: "No seller fees. The buyer pays a small \"buyer protection\" fee.",
    bestFor: "Clothing, shoes, accessories, and (in the US) home goods and some electronics.",
    firstTime: [
      "Clothing-first, no seller fees. The buyer pays the fee.",
      "Sign up with email or phone. You'll add a bank account when you get your first sale.",
      "Vinted picks the shipping label for you; you print it or show a QR code at the drop-off.",
    ],
    before: ["Save the photos.", "Install Vinted, create an account, verify your phone."],
    steps: [
      "Open Vinted. Tap the \"+\" (Sell) button at the bottom.",
      "Add up to 20 photos.",
      "Title: paste the title. Description: paste the copy.",
      "Category, brand, size, condition, color: pick them.",
      "Price: type it. Vinted shows what the buyer will pay after fees.",
      "Package size: pick small/medium/large; that sets the shipping options.",
      "Tap \"Upload\". When it sells, you get a prepaid label; ship within 5 days.",
    ],
    tips: ["One listing per item. Never hashtag a brand other than the item's own, and no links to other sites.", "Bundle discounts (Profile → Bundle discounts) move slow items.", "Mark items \"Sold elsewhere\" right away if they sell locally, or Vinted will penalize cancellations."],
  },
  depop: {
    app: "Depop",
    fees: "No selling fee in the US as of 2024; buyers pay a marketplace fee. Payment processing about 3.3% + 45¢.",
    bestFor: "Vintage clothing, streetwear, Y2K, retro electronics and décor. Young buyers.",
    firstTime: [
      "Trendy clothes and vintage. Sign up with email; it connects to PayPal or its own payments.",
      "Photos matter more than words here; square photos work best.",
      "\"Bump\" means paying to move your item up; not worth it for most items.",
    ],
    before: ["Save the photos; Depop is very visual, so the clean-background photos help.", "Install Depop and create an account."],
    steps: [
      "Open Depop. Tap the camera icon at the bottom.",
      "Add up to 8 photos (and a short video if you have one).",
      "Description: paste the copy. Depop has no separate title; the first line acts as one.",
      "Hashtags: the copy includes some; keep 5.",
      "Category, brand, condition, size, color: pick them.",
      "Price and shipping: choose \"Depop shipping\" for a prepaid label, or your own.",
      "Tap \"Post\".",
    ],
    tips: ["Up to 5 hashtags that describe the item, and no email addresses or talk of selling somewhere else.", "Refresh listings by editing them; Depop bumps edited items.", "Follow and like similar shops; Depop rewards activity with visibility."],
  },
  etsy: {
    app: "Etsy",
    fees: "20¢ per listing, 6.5% transaction fee, plus 3% + 25¢ payment processing.",
    bestFor: "Vintage items (must be 20+ years old), handmade, and craft supplies. Nothing else is allowed.",
    firstTime: [
      "Etsy is for handmade, vintage (20+ years old), and craft supplies. Regular used stuff isn't allowed.",
      "Opening a shop asks for a shop name, bank account, and a credit card on file for fees. Takes 15 minutes.",
      "Each listing costs 20 cents to post, whether it sells or not.",
    ],
    before: ["Confirm the item is vintage (20+ years) or handmade.", "Open a shop at etsy.com/sell (one-time: shop name, bank, ID). Use the \"Etsy Seller\" app after that."],
    steps: [
      "Open the Etsy Seller app. Tap \"Listings\", then \"+\".",
      "Add up to 10 photos and an optional video.",
      "Title: paste the 140-character title. Put the most searched words first (\"Vintage 1970s Technics turntable…\").",
      "About this listing: \"Vintage\" → pick the decade. (Or \"Handmade\".)",
      "Category: Etsy suggests from your title; accept or change.",
      "Description: paste the copy.",
      "Tags: paste the 13 tags from the copy, one at a time.",
      "Price, quantity 1, shipping profile (create one with weight and size; Etsy calculates).",
      "Tap \"Publish\". 20¢ is charged.",
    ],
    tips: ["Only vintage (20+ years old) or handmade items. Reselling newer store-bought things can get your Etsy shop suspended.", "Etsy search runs on your tags and title; use all 13 tags.", "Renew (20¢) rather than relist to keep your reviews.", "Offer free shipping on items over $35; Etsy promotes those."],
  },
};

/** Words the other apps use, in plain English. */
export const GLOSSARY: [string, string][] = [
  ["Listing", "Your item's page: photos, title, price, description."],
  ["Handling time", "How many days after they pay you promise to mail it."],
  ["Calculated shipping", "The buyer's shipping cost is figured from the weight and their ZIP code."],
  ["Flat rate", "One shipping price for everyone."],
  ["Buy It Now", "A set price; no bidding."],
  ["Auction", "Buyers bid; highest bid wins when time runs out."],
  ["Best offer / Offers", "Buyers can suggest a lower price; you accept or decline."],
  ["Item specifics", "Boxes for brand, model, color, size."],
  ["Payout", "The money going from the app to your bank."],
  ["Tracking number", "The code on the shipping label that shows where the package is."],
  ["Renew / Bump / Relist", "Moving your listing back to the top."],
  ["Local pickup", "The buyer comes to get it; no shipping."],
];
