/** Plain-language, phone-first instructions for posting a listing on each marketplace.
 *  Written for someone who has never sold online. Apps move buttons around; steps stay close enough to follow. */
export interface HowTo { app: string; fees: string; bestFor: string; before: string[]; steps: string[]; tips: string[] }

export const HOWTO: Record<string, HowTo> = {
  facebook: {
    app: "Facebook Marketplace",
    fees: "Free for local pickup. If you ship through Facebook, they take 5% (min 40¢).",
    bestFor: "Anything local: furniture, tools, lamps, electronics, big items.",
    before: ["Save the item's photos to your phone (press and hold a photo above → Save).", "Have the Facebook app installed and be signed in."],
    steps: [
      "Open Facebook. Tap the Marketplace icon (the little storefront at the bottom or in the ≡ menu).",
      "Tap \"Sell\" (or \"+ Create new listing\"), then \"Items\".",
      "Tap \"Add photos\" and pick the photos you saved. Choose up to 10. The first one is the cover.",
      "Title: paste the first line from the copy above (press and hold in the box → Paste).",
      "Price: type the price. Category: pick the closest one (Facebook suggests one; check it).",
      "Condition: pick the one that matches what's above.",
      "Description: paste the rest of the copy.",
      "Location: your town. Leave \"Hide from friends\" off unless you want that.",
      "Tap \"Next\". If it offers to post to groups too, tick your local buy/sell groups and this app's group.",
      "Tap \"Publish\". It's live. Messages come to Messenger.",
    ],
    tips: ["Answer \"Is this available?\" fast; Facebook ranks quick responders higher.", "Renew the listing every 7 days (Marketplace → Your listings → Renew) to stay near the top.", "Meet in a public place or at the warehouse; cash or Zelle in person only."],
  },
  offerup: {
    app: "OfferUp",
    fees: "Free for local. Shipping sales: 12.9% (min $1.99).",
    bestFor: "Local buyers, electronics, tools, furniture. Strong in cities.",
    before: ["Save the photos to your phone.", "Install the OfferUp app and create an account (phone number verification)."],
    steps: [
      "Open OfferUp. Tap the big \"Post\" button at the bottom.",
      "Tap \"Take photo\" or the gallery icon and choose your saved photos (up to 12).",
      "Title: paste the title. Category: pick one. Condition: pick one.",
      "Description: paste the copy above.",
      "Price: type it. Turn \"Firm on price\" off; OfferUp buyers expect to haggle.",
      "Delivery: tick \"Local pickup\" and, if you'll ship, \"Shipping\" (OfferUp gives you a prepaid label; the buyer pays for it).",
      "Tap \"Post\". Done.",
    ],
    tips: ["Add your ZIP so it shows in local search.", "Use \"Promote\" only for items over $100; it costs a few dollars.", "Verify your profile (TruYou) once; buyers trust it."],
  },
  ebay: {
    app: "eBay",
    fees: "About 13.6% of the total (item + shipping) plus 30¢ per order for most categories. Free to list (250 a month).",
    bestFor: "Anything shippable with brand names: audio, tools, parts, collectibles, vintage. Biggest audience.",
    before: ["Save the photos.", "Install the eBay app, create an account, add a payout bank account (Payments → Set up)."],
    steps: [
      "Open eBay. Tap \"Selling\" at the bottom, then \"List an item\".",
      "Type the brand and model in the search box. If eBay finds a matching product, tap it; it fills in specs for you. If not, tap \"Create a new listing\".",
      "Tap \"Add photos\" and choose up to 24. First photo = main photo; plain background helps.",
      "Title: paste the 80-character title from the copy. Every word counts for search; no \"L@@K\".",
      "Condition: choose it and add the condition notes.",
      "Item specifics: fill in brand, model, type, color. More = better search placement.",
      "Description: paste the description.",
      "Format: \"Buy It Now\" for most things. For rare items with no clear price, choose \"Auction\", 7 days, start at 99¢ only if you're sure it'll get bids.",
      "Price: eBay shows what similar items sold for; tap that to see. Turn on \"Allow offers\".",
      "Shipping: \"Calculated\" with the weight and box size, or \"Flat\" if you know the cost. Tick \"Local pickup\" too if you want.",
      "Returns: 30 days is the norm and gets a search boost; \"No returns\" is allowed.",
      "Tap \"List it\". Buyers pay through eBay; you ship within your handling time, and eBay pays your bank in 1–2 days.",
    ],
    tips: ["Check \"Sold items\" (search → Filter → Sold) before pricing; that's the real market.", "Print eBay's shipping labels in the app; they're cheaper than the post office counter.", "Ship within a day and buyers rate you higher, which raises your listings."],
  },
  craigslist: {
    app: "Craigslist",
    fees: "Free for almost everything (cars and some services cost $5).",
    bestFor: "Local, cash, older buyers, contractors, big items, lots and pallets.",
    before: ["Save the photos.", "Go to craigslist.org in your phone's browser and pick your city."],
    steps: [
      "Tap \"create a posting\" (top left).",
      "Choose \"for sale by owner\", then the category closest to your item.",
      "Posting title: paste the title. Price: type it. Postal code: yours.",
      "Description: paste the copy.",
      "Contact: choose \"CL mail relay\" so your email stays hidden. Add a phone only if you want texts.",
      "Tap \"continue\". Add a map location if you like (or just the town).",
      "Tap \"add images\" and upload your photos (up to 24).",
      "Tap \"done with images\", check the preview, tap \"publish\".",
      "Check your email and click the confirmation link. Without that click the ad never goes live.",
    ],
    tips: ["Renew every 48 hours (the email link or your account page) to jump back to the top.", "Craigslist has scammers offering to pay by check or \"send a mover\". Cash in person only.", "One item per ad works better than a long list."],
  },
  mercari: {
    app: "Mercari",
    fees: "Currently no seller fee; the buyer pays a service fee at checkout. (Mercari has changed this before; check the app.)",
    bestFor: "Shippable items under $200: electronics, kitchen, toys, small collectibles.",
    before: ["Save the photos.", "Install Mercari and create an account; add your bank for payouts."],
    steps: [
      "Open Mercari. Tap \"Sell\" (the camera icon at the bottom).",
      "Add up to 12 photos.",
      "Title: paste the title. Description: paste the copy.",
      "Category, brand, condition: pick them.",
      "Shipping: choose \"Mercari prepaid label\" and enter the weight; pick who pays (buyer-paid shipping is normal).",
      "Price: type it. Turn on \"Smart Pricing\" only if you're happy with the floor price it asks for.",
      "Tap \"List\". When it sells, print the label from the app and ship within 3 days.",
    ],
    tips: ["Promote (drop the price 5%) once a week; Mercari notifies people who liked it.", "Package well; the buyer has 3 days to rate before you're paid."],
  },
  poshmark: {
    app: "Poshmark",
    fees: "20% on sales over $15; flat $2.95 under $15. Buyer pays shipping.",
    bestFor: "Clothing, shoes, handbags, home décor, and some electronics. Brand names sell.",
    before: ["Save the photos; square photos look best.", "Install Poshmark and create an account."],
    steps: [
      "Open Poshmark. Tap \"Sell\" at the bottom.",
      "Add up to 16 photos. The first is the \"covershot\"; make it clean.",
      "Title: paste the title (80 characters max). Description: paste the copy.",
      "Category, size (if clothing), brand, color, condition: pick them.",
      "Original price and Listing price: fill both (Poshmark shows the markdown).",
      "Tap \"List this item\".",
      "Buyers pay Poshmark; you get a prepaid USPS label by email. Ship within 2 days.",
    ],
    tips: ["Share your listing to your followers daily and join \"Posh Parties\"; that's how things get seen.", "Price 20–30% above your bottom line and accept reasonable offers.", "Add measurements for anything clothing or furniture."],
  },
  vinted: {
    app: "Vinted",
    fees: "No seller fees. The buyer pays a small \"buyer protection\" fee.",
    bestFor: "Clothing, shoes, accessories, and (in the US) home goods and some electronics.",
    before: ["Save the photos.", "Install Vinted, create an account, verify your phone."],
    steps: [
      "Open Vinted. Tap the \"+\" (Sell) button at the bottom.",
      "Add up to 20 photos.",
      "Title: paste the title. Description: paste the copy.",
      "Category, brand, size, condition, color: pick them.",
      "Price: type it. Vinted shows what the buyer will pay after fees.",
      "Package size: pick small/medium/large; that sets the shipping options.",
      "Tap \"Upload\". When it sells, you get a prepaid label; ship within 5 days.",
    ],
    tips: ["Bundle discounts (Profile → Bundle discounts) move slow items.", "Mark items \"Sold elsewhere\" right away if they sell locally, or Vinted will penalize cancellations."],
  },
  depop: {
    app: "Depop",
    fees: "No selling fee in the US as of 2024; buyers pay a marketplace fee. Payment processing about 3.3% + 45¢.",
    bestFor: "Vintage clothing, streetwear, Y2K, retro electronics and décor. Young buyers.",
    before: ["Save the photos; Depop is very visual, so the clean-background photos help.", "Install Depop and create an account."],
    steps: [
      "Open Depop. Tap the camera icon at the bottom.",
      "Add up to 8 photos (and a short video if you have one).",
      "Description: paste the copy. Depop has no separate title; the first line acts as one.",
      "Hashtags: the copy includes some; keep 5.",
      "Category, brand, condition, size, color: pick them.",
      "Price and shipping: choose \"Depop shipping\" for a prepaid label, or your own.",
      "Tap \"Post\".",
    ],
    tips: ["Refresh listings by editing them; Depop bumps edited items.", "Follow and like similar shops; Depop rewards activity with visibility."],
  },
  etsy: {
    app: "Etsy",
    fees: "20¢ per listing, 6.5% transaction fee, plus 3% + 25¢ payment processing.",
    bestFor: "Vintage items (must be 20+ years old), handmade, and craft supplies. Nothing else is allowed.",
    before: ["Confirm the item is vintage (20+ years) or handmade.", "Open a shop at etsy.com/sell (one-time: shop name, bank, ID). Use the \"Etsy Seller\" app after that."],
    steps: [
      "Open the Etsy Seller app. Tap \"Listings\", then \"+\".",
      "Add up to 10 photos and an optional video.",
      "Title: paste the 140-character title. Put the most searched words first (\"Vintage 1970s Technics turntable…\").",
      "About this listing: \"Vintage\" → pick the decade. (Or \"Handmade\".)",
      "Category: Etsy suggests from your title; accept or change.",
      "Description: paste the copy.",
      "Tags: paste the 13 tags from the copy, one at a time.",
      "Price, quantity 1, shipping profile (create one with weight and size; Etsy calculates).",
      "Tap \"Publish\". 20¢ is charged.",
    ],
    tips: ["Etsy search runs on your tags and title; use all 13 tags.", "Renew (20¢) rather than relist to keep your reviews.", "Offer free shipping on items over $35; Etsy promotes those."],
  },
};
