import StoreHeader from "../StoreHeader";
import { getBusiness } from "@/lib/business";

export const metadata = { title: "Terms of Service" };

export default async function TermsPage() {
  const business = await getBusiness();
  const where = business.address || business.location || "";
  const reach = [business.contact_phone, business.contact_email].filter(Boolean).join(" · ");
  return (
    <div className="flex-1">
      <StoreHeader business={business} />
      <main className="max-w-3xl mx-auto p-4 space-y-6 text-sm">
        <div><h1 className="text-2xl font-bold">Terms of Service</h1><p className="muted">Next Owner Market · Last updated October 5, 2026 · Operated by {business.name}{where ? `, ${where}` : ""}{reach ? ` · ${reach}` : ""}</p></div>
        <p>These are written in plain language on purpose. By creating an account, listing, buying, or messaging on nextownermarket.com you agree to them.</p>
        <section className="space-y-2"><h2 className="font-semibold text-lg">1. Who we are</h2><p>Next Owner Market (nextownermarket.com) is an online marketplace operated by {business.name}{where ? `, ${where}` : ""} (the &quot;Company&quot;). We provide the listing tools, the storefront, and payment processing. Unless an item is listed by our own staff, the seller, not the Company, is the party selling the item.</p></section>
        <section className="space-y-2"><h2 className="font-semibold text-lg">2. Accounts</h2><ul className="list-disc pl-5 space-y-1"><li>You must be 18 or older and provide accurate contact information.</li><li>One account per person or business. We may suspend or close accounts that break these terms.</li><li>Sellers must complete payout verification with our payment processor (Stripe) before they can sell through checkout.</li></ul></section>
        <section className="space-y-2"><h2 className="font-semibold text-lg">3. Listings</h2><ul className="list-disc pl-5 space-y-1"><li>Describe items accurately, including defects. Photos must be of the actual item.</li><li>Prohibited: illegal items, recalled products, weapons and ammunition, counterfeits, stolen goods, items you don&apos;t have the right to sell, and anything that violates Stripe&apos;s or the law&apos;s restrictions.</li><li>Contact details and off-platform payment instructions are removed from public listings. All store sales go through checkout so both sides are protected.</li><li>Free accounts may keep 10 live listings. Paying members (Pro and Power Seller) have no listing limit.</li><li>We may remove any listing at our discretion.</li></ul></section>
        <section className="space-y-2"><h2 className="font-semibold text-lg">4. Buying and held payment</h2><ul className="list-disc pl-5 space-y-1"><li>When you buy, you pay the full amount to our payment processor. The seller is paid only after hand-off is confirmed.</li><li><b>Pickup:</b> you receive a pickup code. Give it to the seller only when the item is in your hands. If pickup doesn&apos;t happen within 7 days, you are refunded automatically.</li><li><b>Shipping:</b> the seller must add tracking. Payment releases when you confirm receipt, or 3 days after delivery if no problem is reported.</li><li>Report problems from the order page before payment is released. After release, sales are final except as required by law. Full details: <a href="/returns" className="underline">Returns and refunds</a> and <a href="/shipping" className="underline">Shipping</a>.</li></ul></section>
        <section className="space-y-2"><h2 className="font-semibold text-lg">5. Fees</h2><ul className="list-disc pl-5 space-y-1"><li>Listing is free. Store sales pay a commission on the item price (not shipping): self-listed 15%, drop-off consignment 30%, full-service consignment 40% (50% under $50). Rates may change with notice.</li><li>Pro membership is $15/month, billed monthly, cancel any time. Pro includes 300 AI uses a month (an AI use is one listing written, one lookup, one pile sorted, or one Buy or Pass check past the daily free ones), ready-to-paste cross-posting text, video, and unlimited live listings. Power Seller is $39/month for 1,000 AI uses a month. Thrift Pro is $3.99/month for up to 30 checks a day. Extra AI uses can be bought in packs; packs never expire and are not refundable once used. Comped (gifted) memberships have no monthly limit.</li><li>Card processing fees are included in our commission; sellers are not charged separately.</li></ul></section>
        <section className="space-y-2"><h2 className="font-semibold text-lg">6. Payouts</h2><ul className="list-disc pl-5 space-y-1"><li>Seller payouts go to the bank account verified with Stripe, normally within 2 business days of release.</li><li>We may hold or reverse payouts for suspected fraud, chargebacks, or unresolved problem reports.</li><li>Sellers are responsible for their own taxes. Stripe issues tax forms where required by law.</li></ul></section>
        <section className="space-y-2"><h2 className="font-semibold text-lg">7. Problems, refunds, and disputes</h2><ul className="list-disc pl-5 space-y-1"><li>Either party may report a problem on an open order. Funds are frozen until the Company decides.</li><li>The Company decides in good faith based on the listing, photos, messages, and evidence provided. Decisions may be a full refund to the buyer or release to the seller.</li><li>Card chargebacks filed with a bank are handled through Stripe; abusing chargebacks results in account closure.</li></ul></section>
        <section className="space-y-2"><h2 className="font-semibold text-lg">8. Ratings and conduct</h2><ul className="list-disc pl-5 space-y-1"><li>Both parties may rate each other after a completed order. Ratings must be honest and about the transaction.</li><li>No harassment, threats, or discrimination. Meet in safe, public places or at the Company&apos;s warehouse during posted hours.</li></ul></section>
        <section className="space-y-2"><h2 className="font-semibold text-lg">9. Consignment (items handed to the Company)</h2><ul className="list-disc pl-5 space-y-1"><li>For full-service and drop-off consignment, the Company photographs, lists, stores, and sells the item and remits the consignor&apos;s share after sale.</li><li>Unsold items may be returned, donated, or discounted after the consignment period agreed at drop-off, with notice.</li><li>The Company is not responsible for loss or damage beyond the agreed consignment value.</li></ul></section>
        <section className="space-y-2"><h2 className="font-semibold text-lg">10. Liability</h2><ul className="list-disc pl-5 space-y-1"><li>Items are sold as described, used unless stated otherwise. To the extent permitted by law, the Company&apos;s liability is limited to the amount paid for the order in question.</li><li>The Company is not a party to sales between members and makes no warranty about items listed by others.</li></ul></section>
        <section className="space-y-2"><h2 className="font-semibold text-lg">11. Privacy</h2><ul className="list-disc pl-5 space-y-1"><li>We collect the information needed to run the marketplace (name, contact, order history). Payment and identity details are collected by Stripe under its privacy policy; we never see card numbers or bank details.</li><li>We send transactional messages (order updates) and, if you opted in, new-arrival alerts. Unsubscribe any time.</li><li>We never sell your information.</li></ul></section>
        <section className="space-y-2"><h2 className="font-semibold text-lg">12. Changes</h2><p>We may update these terms; continued use after notice means acceptance. Governing law: Commonwealth of Virginia.</p><p>Contact: {business.name}{where ? `, ${where}` : ""}{reach ? ` · ${reach}` : ""} · <a href="/contact" className="underline">Contact page</a></p></section>
      </main>
    </div>
  );
}
