-- Offers (make_offer / respond_offer / buyer_offer), orders.offer_id + label_cost/label_url/tracking_url (seller_due subtracts label cost),
-- profiles.address1/2 (ship-from), private 'backups' storage bucket. Full bodies in applied migration offers_labels_backups.
-- security_hardening_2: anon cannot call account-only RPCs; trigger functions not callable; strip_contact search_path fixed
-- pickups_by_order: pickups.order_id/buyer_id; book_pickup(order, slot, note) auto-confirms warehouse slots; pickups public insert removed
-- profiles_column_lock: authenticated may update only contact columns on profiles; staff changes go through staff_update_profile(uuid, jsonb)
-- geo_search: profiles.lat/lng, seller_public gains city/state/lat/lng, search_items(...) RPC with state + radius filters; items_trust_guard requires seller ZIP/state to list
-- become_seller(): a signed-in buyer becomes a consignor (pending approval), keeps the account
-- calculated_shipping: items.box, items.shipping_mode (calculated|flat|free); orders.shipping_rate_id/shipping_service
-- shipping_margin: orders.shipping_mode; seller_due excludes calculated shipping when the platform bought the label; settings.business.shipping_markup_pct/min
-- shipping_two_modes: flat removed (mapped to calculated); seller_due = amount - commission, minus label cost only on free-shipping orders
