-- Offers (make_offer / respond_offer / buyer_offer), orders.offer_id + label_cost/label_url/tracking_url (seller_due subtracts label cost),
-- profiles.address1/2 (ship-from), private 'backups' storage bucket. Full bodies in applied migration offers_labels_backups.
-- security_hardening_2: anon cannot call account-only RPCs; trigger functions not callable; strip_contact search_path fixed
